/**
 * Renders an inline SVG poster produced by the studio engine. The SVG is fully
 * generated by our own code (no user HTML), so injecting it is safe.
 */
export function Poster({ svg, className }: { svg: string; className?: string }) {
  return (
    <div
      className={className ?? "poster-wrap"}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
